In [38]:

#import all the necessary libraries

import pandas as pd
import numpy as np
import pandas as pd

# For Visualisation
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# To Scale our data
from sklearn.preprocessing import scale

# To perform KMeans clustering 
from sklearn.cluster import KMeans

# To perform Hierarchical clustering
from scipy.cluster.hierarchy import linkage
from scipy.cluster.hierarchy import dendrogram
from scipy.cluster.hierarchy import cut_tree

ModuleNotFoundError: No module named 'matplotlib'

In [75]:
#let's read the dataset
dat = pd.read_csv('../dataset/dataset.csv')
dat.head()

full_path  \
0  /C/Harshad.Ambekar/NICE/bitbucket/saas-platfor...   
1  /C/Harshad.Ambekar/NICE/bitbucket/saas-platfor...   
2  /C/Harshad.Ambekar/NICE/bitbucket/saas-platfor...   
3  /C/Harshad.Ambekar/NICE/bitbucket/saas-platfor...   
4  /C/Harshad.Ambekar/NICE/bitbucket/saas-platfor...   

                      file_name  \
0                 all-files.csv   
1                       pom.xml   
2                   Legacy.java   
3  TenantManagerAPIVersion.java   
4   ApplicationUserDetails.java   

                                            dir_path  \
0  /C/Harshad.Ambekar/NICE/bitbucket/saas-platfor...   
1  /C/Harshad.Ambekar/NICE/bitbucket/saas-platfor...   
2  /C/Harshad.Ambekar/NICE/bitbucket/saas-platfor...   
3  /C/Harshad.Ambekar/NICE/bitbucket/saas-platfor...   
4  /C/Harshad.Ambekar/NICE/bitbucket/saas-platfor...   

                              repo  loginflow  tenantflow  authenflow  \
0  saas-platform-ms-tenant-manager          0           0           0   
1  saas-platform-ms-tenant-manager          1           1           1   
2  saas-platform-ms-tenant-manager          0           0           1   
3  saas-platform-ms-tenant-manager          0           1           1   
4  saas-platform-ms-tenant-manager          0           1           0   

   authflow  usercreation  tenantcreation  tenantmodifcation  
0         1             0               1                  0  
1         0             0               1                  0  
2         1             0               1                  0  
3         1             1               1                  0  
4         1             1               0                  0

In [40]:
plt.figure(figsize = (20,10))        
sns.heatmap(dat.corr(),annot = True)

NameError: name 'plt' is not defined

In [41]:
#The final matrix would only contain the data columns. Hence let's drop the country column
datm=dat.drop(['full_path', 'file_name', 'dir_path', 'repo'],axis=1)
datm.head()

loginflow  tenantflow  authenflow  authflow  usercreation  tenantcreation  \
0          0           0           0         1             0               1   
1          1           1           1         0             0               1   
2          0           0           1         1             0               1   
3          0           1           1         1             1               1   
4          0           1           0         1             1               0   

   tenantmodifcation  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0

In [42]:
#we observe that a lot of the data variables are of different orders of magnitude. 
#Let's do rescaling so that PCA can be applied.
from sklearn.preprocessing import StandardScaler
standard_scaler = StandardScaler()
dat2 = standard_scaler.fit_transform(datm)

In [43]:
dat2

array([[-0.9826846 , -1.00313973, -0.98004676, ..., -0.99330499,
         0.99865742, -1.01035364],
       [ 1.01762051,  0.9968701 ,  1.02035947, ..., -0.99330499,
         0.99865742, -1.01035364],
       [-0.9826846 , -1.00313973,  1.02035947, ..., -0.99330499,
         0.99865742, -1.01035364],
       ...,
       [-0.9826846 , -1.00313973, -0.98004676, ...,  1.00674013,
        -1.00134439, -1.01035364],
       [ 1.01762051,  0.9968701 , -0.98004676, ...,  1.00674013,
        -1.00134439,  0.98975246],
       [ 1.01762051,  0.9968701 , -0.98004676, ...,  1.00674013,
        -1.00134439,  0.98975246]])

In [44]:
#Importing the PCA module
from sklearn.decomposition import PCA
pca = PCA(svd_solver='randomized', random_state=42)

In [45]:
#let's apply PCA
pca.fit(dat2)

PCA(random_state=42, svd_solver='randomized')

In [46]:
#List of PCA components.It would be the same as the number of variables
pca.components_

array([[ 3.06429665e-01,  5.58649172e-01,  3.89673176e-01,
         2.21088202e-01,  1.35111889e-02,  6.00968054e-01,
         1.78722220e-01],
       [ 1.76351225e-01, -3.26837364e-01, -4.18874221e-02,
         5.63895234e-01, -5.29068844e-01,  1.87305959e-01,
        -4.76810055e-01],
       [ 4.94142781e-01, -2.33437521e-01,  4.52234739e-01,
        -4.58780731e-01, -4.57381738e-01, -2.04891481e-01,
         1.87497317e-01],
       [-4.38156886e-01,  1.39368107e-01,  5.78277794e-01,
        -2.47833657e-01,  2.09448267e-02, -4.12738423e-03,
        -6.26348644e-01],
       [ 5.30690469e-01,  1.42821950e-01,  1.49316226e-01,
         2.92494798e-01,  4.69757482e-01, -5.29680593e-01,
        -2.98139820e-01],
       [ 1.83620863e-02, -6.97691695e-01,  3.26583132e-01,
         7.69550201e-02,  5.11974105e-01,  3.52592299e-01,
         1.17778189e-01],
       [-3.96071989e-01,  2.90653340e-04,  4.22524456e-01,
         5.19389651e-01, -1.65762752e-01, -3.96072546e-01,
         4.5878493

In [47]:
#Let's check the variance ratios
pca.explained_variance_ratio_

array([0.1542032 , 0.15160693, 0.14876432, 0.14625555, 0.13993255,
       0.13298828, 0.12624917])

In [48]:
#Plotting the scree plot
#Making the screeplot - plotting the cumulative variance against the number of components
%matplotlib inline
fig = plt.figure(figsize = (12,8))
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.xlabel('number of components')
plt.ylabel('cumulative explained variance')
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

In [49]:
#Let's try and check the first three components now
colnames = list(dat.drop(['full_path', 'file_name', 'dir_path', 'repo'],axis=1).columns)
pcs_df = pd.DataFrame({ 'Feature':colnames,'PC1':pca.components_[0],'PC2':pca.components_[1],'PC3':pca.components_[2]})
pcs_df

Feature       PC1       PC2       PC3
0          loginflow  0.306430  0.176351  0.494143
1         tenantflow  0.558649 -0.326837 -0.233438
2         authenflow  0.389673 -0.041887  0.452235
3           authflow  0.221088  0.563895 -0.458781
4       usercreation  0.013511 -0.529069 -0.457382
5     tenantcreation  0.600968  0.187306 -0.204891
6  tenantmodifcation  0.178722 -0.476810  0.187497

In [50]:
#Let's visualise the first 2 components
%matplotlib inline
fig = plt.figure(figsize = (8,8))
plt.scatter(pcs_df.PC1, pcs_df.PC2)
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
for i, txt in enumerate(pcs_df.Feature):
    plt.annotate(txt, (pcs_df.PC1[i],pcs_df.PC2[i]))
plt.tight_layout()
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

In [51]:
#We are observing 90% variance with 3 principal components. So let's take the data until that many components
#Using incremental PCA for efficiency - saves a lot of time on larger datasets
from sklearn.decomposition import IncrementalPCA
pca_final = IncrementalPCA(n_components=3)

In [52]:
#let's project our original data on the 3 principal components
df_train_pca = pca_final.fit_transform(dat2)
df_train_pca.shape

(2233, 3)

In [53]:

#take the transpose of the PC matrix so that we can create the new matrix
pc = np.transpose(df_train_pca)
pc

array([[-2.09471622,  0.60121231, -1.57252198, ..., -1.22021438,
         0.97526489,  1.57260259],
       [ 0.25505427, -1.81159702, -0.71162741, ...,  1.13486676,
         1.19945555,  0.68607468],
       [ 1.26997086, -0.12762606,  0.48426198, ..., -1.06872554,
         0.17969785, -0.49059424]])

In [54]:
#Let's create the newer matrix according to the given principal components
rownames = list(dat['full_path'])
pcs_df2 = pd.DataFrame({'full_path':rownames,'PC1':pc[0],'PC2':pc[1],'PC3':pc[2]})
pcs_df2.head()

full_path       PC1       PC2  \
0  /C/Harshad.Ambekar/NICE/bitbucket/saas-platfor... -2.094716  0.255054   
1  /C/Harshad.Ambekar/NICE/bitbucket/saas-platfor...  0.601212 -1.811597   
2  /C/Harshad.Ambekar/NICE/bitbucket/saas-platfor... -1.572522 -0.711627   
3  /C/Harshad.Ambekar/NICE/bitbucket/saas-platfor...  0.108594  0.956524   
4  /C/Harshad.Ambekar/NICE/bitbucket/saas-platfor... -0.753806  2.089127   

        PC3  
0  1.269971  
1 -0.127626  
2  0.484262  
3 -0.138425  
4 -0.834166

In [55]:
#Let's do the outlier analysis before proceeding to clustering
#We can reassign the outliers to the clusters later
plt.boxplot(pcs_df2.PC1)
Q1 = pcs_df2.PC1.quantile(0.05)
Q3 = pcs_df2.PC1.quantile(0.95)
IQR = Q3 - Q1
pcs_df2 = pcs_df2[(pcs_df2.PC1 >= Q1) & (pcs_df2.PC1 <= Q3)]

NameError: name 'plt' is not defined

In [56]:
plt.boxplot(pcs_df2.PC2)
Q1 = pcs_df2.PC2.quantile(0.05)
Q3 = pcs_df2.PC2.quantile(0.95)
IQR = Q3 - Q1
pcs_df2 = pcs_df2[(pcs_df2.PC2 >= Q1) & (pcs_df2.PC2 <= Q3)]

NameError: name 'plt' is not defined

In [57]:
plt.boxplot(pcs_df2.PC3)
Q1 = pcs_df2.PC3.quantile(0.05)
Q3 = pcs_df2.PC3.quantile(0.95)
IQR = Q3 - Q1
dat3 = pcs_df2[(pcs_df2.PC3 >= Q1 ) & (pcs_df2.PC3 <= Q3)]

NameError: name 'plt' is not defined

In [58]:

#Outlier analysis is now done.Let's check the data again.
pcs_df2.shape

(2233, 4)

In [59]:
#let's check the spread of the dataset
sns.scatterplot(x='PC1',y='PC2',data=pcs_df2)

NameError: name 'sns' is not defined

In [60]:
#Calculating the Hopkins statistic
from sklearn.neighbors import NearestNeighbors
from random import sample
from numpy.random import uniform
import numpy as np
from math import isnan
 
def hopkins(X):
    d = X.shape[1]
    #d = len(vars) # columns
    n = len(X) # rows
    m = int(0.1 * n) 
    nbrs = NearestNeighbors(n_neighbors=1).fit(X.values)
 
    rand_X = sample(range(0, n, 1), m)
 
    ujd = []
    wjd = []
    for j in range(0, m):
        u_dist, _ = nbrs.kneighbors(uniform(np.amin(X,axis=0),np.amax(X,axis=0),d).reshape(1, -1), 2, return_distance=True)
        ujd.append(u_dist[0][1])
        w_dist, _ = nbrs.kneighbors(X.iloc[rand_X[j]].values.reshape(1, -1), 2, return_distance=True)
        wjd.append(w_dist[0][1])
 
    H = sum(ujd) / (sum(ujd) + sum(wjd))
    if isnan(H):
        print(ujd, wjd)
        H = 0
 
    return H

In [61]:
#Let's check the Hopkins measure
hopkins(pcs_df2.drop(['full_path'],axis=1))

1.0

In [62]:
#0.83 is a good Hopkins score. Hence the data is suitable for clustering. Preliminary check is now done.
#We can do standardisation again or else we can skip this step as well.
dat3 = pcs_df2
dat3_1 = standard_scaler.fit_transform(dat3.drop(['full_path'],axis=1))

In [63]:
#Let's check the silhouette score first to identify the ideal number of clusters
from sklearn.metrics import silhouette_score
sse_ = []
for k in range(2, 10):
    kmeans = KMeans(n_clusters=k).fit(dat3_1)
    sse_.append([k, silhouette_score(dat3_1, kmeans.labels_)])

NameError: name 'KMeans' is not defined

In [64]:
plt.plot(pd.DataFrame(sse_)[0], pd.DataFrame(sse_)[1]);

NameError: name 'plt' is not defined

In [65]:
#The sihouette score reaches a peak at around 5 clusters indicating that it might be the ideal number of clusters.
#Let's use the elbow curve method to identify the ideal number of clusters.
ssd = []
for num_clusters in list(range(1,10)):
    model_clus = KMeans(n_clusters = num_clusters, max_iter=50)
    model_clus.fit(dat3_1)
    ssd.append(model_clus.inertia_)

plt.plot(ssd)

NameError: name 'KMeans' is not defined

In [66]:

#A distinct elbow is formed at around 3-7 clusters. Let's finally create the clusters and see for ourselves which ones fare better
#K-means with k=5 clusters
model_clus5 = KMeans(n_clusters = 5, max_iter=50)
model_clus5.fit(dat3_1)

NameError: name 'KMeans' is not defined

In [67]:
dat4=dat3
dat4.index = pd.RangeIndex(len(dat4.index))
dat_km = pd.concat([dat4, pd.Series(model_clus5.labels_)], axis=1)
dat_km.columns = ['full_path', 'PC1', 'PC2','PC3','ClusterID']
dat_km.head()

NameError: name 'model_clus5' is not defined

In [68]:
dat_km['ClusterID'].value_counts()

NameError: name 'dat_km' is not defined

In [69]:
#Each cluster has a good number of countries associated with it(at least 5% of the dataset under consideration)
#Let's do some further visualizations.
#We'll be visualising the clusters on the original principal components
sns.scatterplot(x='PC1',y='PC2',hue='ClusterID',legend='full',data=dat_km)

NameError: name 'sns' is not defined

In [70]:
sns.scatterplot(x='PC2',y='PC3',hue='ClusterID',data=dat_km)

NameError: name 'sns' is not defined

In [71]:
sns.scatterplot(x='PC3',y='PC1',hue='ClusterID',data=dat_km)

NameError: name 'sns' is not defined

In [72]:
#One thing we noticed is some even though some distinct clusters are being formed, some are not so good.
#Now let's create the cluster means wrt to the various variables mentioned in the question and plot and see how they are related
dat5=pd.merge(dat,dat_km,on='full_path')
dat6=dat5[['loginflow','tenantflow','authenflow','authflow','usercreation','tenantcreation','tenantmodifcation','ClusterID']]

clu_loginflow = pd.DataFrame(dat6.groupby(["ClusterID"]).loginflow.mean())
clu_tenantflow = pd.DataFrame(dat6.groupby(["ClusterID"]).tenantflow.mean())
clu_authenflow = pd.DataFrame(dat6.groupby(["ClusterID"]).authenflow.mean())
clu_authflow = pd.DataFrame(dat6.groupby(["ClusterID"]).authflow.mean())
clu_usercreation = pd.DataFrame(dat6.groupby(["ClusterID"]).usercreation.mean())
clu_tenantcreation = pd.DataFrame(dat6.groupby(["ClusterID"]).tenantcreation.mean())         
clu_tenantmodifcation = pd.DataFrame(dat6.groupby(["ClusterID"]).tenantmodifcation.mean())

df = pd.concat([pd.Series([0,1,2,3]),clu_loginflow,clu_tenantflow,clu_authenflow,clu_authflow,clu_usercreation,clu_tenantcreation,clu_tenantmodifcation], axis=1)
df.columns = ["ClusterID", "loginflow", "tenantflow", "authenflow","authflow","usercreation","tenantcreation","tenantmodifcation"]
df

NameError: name 'dat_km' is not defined

In [73]:
dat5[dat5['full_path']=='/C/Harshad.Ambekar/NICE/bitbucket/saas-platform-ms-tenant-manager/boot/dev/scaling-policy.json']

NameError: name 'dat5' is not defined

In [74]:
dat5.to_csv('../dataset/result.csv')

NameError: name 'dat5' is not defined